mozilla/glean_parser

README.rst

Hi folks! 👋 
I noticed that the code-blocks don't render correctly.
Hope this helps!

Fix code-block formatting in README.rst

---

glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml

[Bug 1501318](https://bugzilla.mozilla.org/show_bug.cgi?id=1501318)

Add UUID metric type

---

glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2.kt
tests/data/core.yaml
tests/test_kotlin.py
tests/test_parser.py

This should simplify handling of lifetimes in the storage engines / backends.
[1503569](https://bugzilla.mozilla.org/show_bug.cgi?id=1503569)

Change application_property/user_property to lifetime

---

.gitignore
docs/index.rst
glean_parser/util.py

There's still a lot more to do with the docs, but this at least gets us to a working baseline.

Minor improvements to get the docs to build cleanly

---

glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
tests/test_parser.py

This generates the specific metrics for labeled metrics.

1516527: Add support for labeled metrics

---

glean_parser/schemas/metrics.1-0-0.schema.yaml

In response to [this comment](https://github.com/mozilla-mobile/android-components/pull/2185#issuecomment-467930388)

Update time_unit documentation to specifically address truncation

---

README.rst
docs/metrics-yaml.rst
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
setup.py
tests/data/core.yaml
tests/data/smaller.yaml
tests/test_metrics.py
tests/test_parser.py
tests/util.py

The proposal isn't quite finished, but this is a first pass at an implementation anyway, so as to not be blocked.
The fun bit of this is that this should require zero changes in the client.

1528260: Simplify and implement metric expiry

---

glean_parser/metrics.py
glean_parser/pings.py
glean_parser/schemas/pings.1-0-0.schema.yaml
glean_parser/util.py
tests/data/pings.yaml
tests/test_kotlin.py
tests/test_pings.py
tests/util.py

Adds the metadata related to data review and expiration from metrics to pings as well.

1547967: Add additional metadata to pings

---

glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
tests/data/core.yaml

This was easier then expected: I hope I'm not missing anything with this one.

Rename 'string_list' to 'string_set'

---

glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
tests/data/core.yaml

Reverts mozilla/glean_parser#77 (due to the discussion [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/362#issuecomment-515047429)

Revert "Rename 'string_list' to 'string_set'"

---

HISTORY.rst
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

1571744: Add custom_distribution metric type

---

glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml

Draft while I double-check the metric file once more.

Remove labeled string list & UUID

---

HISTORY.rst
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

Memory histogram

---

setup.py

MAINT: Upgrade dependencies

---

HISTORY.rst
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

1573516: Add Quantity metric type

---

HISTORY.rst
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/data/pings.yaml
tests/test_markdown.py
tests/test_parser.py

Reverts mozilla/glean_parser#90

Revert "Restrict ping names to be kebab-case"

---

glean_parser/translate.py
tests/test_translate.py

Don't clear the output dir when generating markdown

---

HISTORY.rst
glean_parser/templates/kotlin.geckoview.jinja2

The Kotlin Gecko output should import LabeledMetricTypes

---

HISTORY.rst
glean_parser/parser.py
tests/test_parser.py

1578719: Add do_not_disable_expired parser config

---

HISTORY.rst
glean_parser/lint.py
tests/test_lint.py

glinter will report about superfluous no_lint entries

---

HISTORY.rst
glean_parser/swift.py
glean_parser/templates/swift.jinja2

Create labeled metrics, events and wrap it in the Glean namespace

---

glean_parser/templates/swift.jinja2

Fix indentation for pings

---

glean_parser/templates/swift.jinja2

At some point I will get the indentation right.

Correct indentation for comments

---

glean_parser/__main__.py

1585722: Glinter should complain when file not found

---

glean_parser/__main__.py
tests/test_cli.py

1586326: Add a --version parameter

---

HISTORY.rst
glean_parser/lint.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/util.py

1585953: Warn when using bug numbers

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/metrics.py

1586749: Don't include Glean internal metrics in the generated markdown

---

HISTORY.rst

Update HISTORY.rst for v1.9.2

---

HISTORY.rst

Fixes [Bug 1587342](https://bugzilla.mozilla.org/show_bug.cgi?id=1587342)

Update HISTORY.rst for release (1.9.3)

---

glean_parser/parser.py

Fix doc formatting

---

HISTORY.rst
glean_parser/pings.py

Reserve the `deletion_request` ping name

---

HISTORY.rst
glean_parser/translate.py
tests/test_translate.py

1589596: Don't delete too many things in the output directory

---

HISTORY.rst
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/data/core.yaml
tests/data/pings.yaml
tests/test_swift.py

Wrap newlines better

---

HISTORY.rst

Release v1.13.0

---

Makefile
requirements_dev.txt
setup.py

MAINT: Run black on all the files

---

HISTORY.rst
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml

Add additional ping names to the allow list

---

HISTORY.rst
Makefile
glean_parser/templates/kotlin.jinja2
glean_parser/util.py
tests/test_kotlin.py

Fix code gen

---

HISTORY.rst

Release v1.15.3

---

HISTORY.rst
glean_parser/schemas/pings.1-0-0.schema.yaml

Allow legacy name `all_pings` and release v1.15.4

---

docs/index.rst
docs/pings-yaml.rst
docs/sphinxext/eval.py
glean_parser/parser.py

Document pings.yaml schema

---

glean_parser/templates/swift.jinja2

Skip import if it is the glean namespace itself

---

HISTORY.rst
docs/pings-yaml.rst
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/pings.py
glean_parser/schemas/pings.1-0-0.schema.yaml
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/test_kotlin.py
tests/test_swift.py

1609218: Add support for reason codes

---

HISTORY.rst
glean_parser/__main__.py
glean_parser/validate_ping.py
tests/test_validate_ping.py

Make 'schema_url' required for 'validate_ping'

---

glean_parser/swift.py
glean_parser/templates/swift.jinja2
tests/test_swift.py

1557048: Updates to support ping reason codes in Swift

---

glean_parser/kotlin.py
tests/test_kotlin.py

Rename empty enum

---

HISTORY.rst

Backport changelog entry for 1.15.6 bugfix release

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml

Document that descriptions may contain markdown syntax

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/templates/markdown.jinja2
tests/data/pings.yaml
tests/test_markdown.py

1613346: Update generated docs to mention reason codes

---

HISTORY.rst
glean_parser/templates/markdown.jinja2

Fix rendering of first element in the reason list

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml

1608585: Fix label regex

---

HISTORY.rst

Update History.rst to prepare for version cut

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/templates/markdown.jinja2

Fixes [Bug 1615221](https://bugzilla.mozilla.org/show_bug.cgi?id=1615221)
* Add info about wether the ping includes client id;
* Add list of data review links;
* Add list of related bugs links.

Add more information to pings md docs

---

tests/data/core.yaml
tests/data/duplicate_labeled.yaml
tests/data/duplicate_send_in_ping.yaml
tests/data/gecko.yaml
tests/data/schema-violation.yaml
tests/data/smaller.yaml

Make unit testing metrics.yaml files glinter-compliant

---

Makefile
glean_parser/kotlin.py
glean_parser/lint.py
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/pings.py
glean_parser/swift.py
glean_parser/translate.py
glean_parser/util.py
glean_parser/validate_ping.py
requirements_dev.txt
requirements_dev_py35.txt
tests/test_kotlin.py
tests/test_markdown.py
tests/test_metrics.py
tests/test_swift.py

Additionally, this fixes the black formatter check in CI and fixes a few
black violations that have slipped through.

MAINT: Add mypy type annotations.

---

docs/pings-yaml.rst
glean_parser/kotlin.py
glean_parser/markdown.py
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/translate.py

Lots of little documentation formatting issues

---

HISTORY.rst
glean_parser/lint.py
tests/test_lint.py

Bug 1636138: Report the correct filename in yamllint errors

---

glean_parser/templates/markdown.jinja2

Fix Jinja2 deprecation

---

HISTORY.rst
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

Enforce a maximum limit of 10 extra_keys for `event`s

---

HISTORY.rst
glean_parser/swift.py
glean_parser/templates/swift.jinja2
tests/test_swift.py

I tested this locally against Glean and the sample app.

Swift: Combine all metrics and pings into a single generated file

---

CONTRIBUTING.rst
HISTORY.rst

New release: 1.22.0

---

HISTORY.rst
glean_parser/metrics.py
tests/data/event_key_ordering.yaml
tests/test_kotlin.py
tests/test_markdown.py
tests/test_swift.py

Bug 1648768: Fix extra key ordering

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/markdown.jinja2
tests/test_markdown.py
tools/extract_data_categories.py

Rename data_categories to data_sensitivity

---

glean_parser/templates/markdown.jinja2

I assume "Data Sensitivity" is the category?

Bug 1654880 - Fix table rendering

---

HISTORY.rst
glean_parser/templates/csharp.jinja2

Generate valid C# code when using Labeled metric types

---

glean_parser/__main__.py

Bug 1656182: Display --version for git-installed glean_parser

---

HISTORY.rst
glean_parser/lint.py
tests/test_lint.py

Bug 1654859: Remove the lintception

---

.circleci/config.yml

Use new pip-resolver

---

HISTORY.rst
docs/metrics-yaml.rst
glean_parser/lint.py
glean_parser/metrics.py
glean_parser/util.py
tests/test_lint.py

Bug 1599764 -  Have glinter warn when expiry date is too far in the future

---

HISTORY.rst
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/util.py
tests/test_metrics.py
tests/test_parser.py

Bug 1664306 - Add Custom Expiry support

---

.circleci/config.yml
Makefile
setup.py

Also (while there) upgrades earlier Python versions to the most recent patch
releases.

Add Python 3.9 to CI

---

glean_parser/csharp.py
glean_parser/kotlin.py
glean_parser/lint.py
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/swift.py
glean_parser/translate.py
requirements_dev.txt
tests/test_parser.py
tests/test_translate.py
tests/util.py

Use bugbear in CI

---

CONTRIBUTING.rst

Bug 1664882: Improve deploy instructions

---

HISTORY.rst
glean_parser/__main__.py
glean_parser/lint.py
glean_parser/parser.py
glean_parser/util.py
tests/test_lint.py
tests/test_parser.py
tests/test_translate.py

Bug 1668798: Fail on absent files, unless --allow-missing-files

---

HISTORY.rst
glean_parser/pings.py
glean_parser/templates/csharp.jinja2
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/test_kotlin.py

Bug 1668547: Incl. metric identifier in comment in gen. code

---

HISTORY.rst
glean_parser/metrics.py
tests/test_metrics.py

Dont always include unit

---

glean_parser/templates/markdown.jinja2

[doc only] Bug 1625412: Mention that all pings contain built-in-metrics

---

.circleci/config.yml

Use final release of Python 3.9.0 in CI

---

glean_parser/markdown.py
glean_parser/templates/markdown.jinja2
tests/test_markdown.py

Data reviews in human readable form

---

HISTORY.rst
glean_parser/lint.py
glean_parser/parser.py
glean_parser/pings.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/data/pings.yaml
tests/test_lint.py
tests/util.py

Bug 1686243: Lint bug URLs in pings

---

CHANGELOG.md
glean_parser/__main__.py
glean_parser/coverage.py
glean_parser/parser.py

Support coverage analysis

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/core.yaml
tests/test_translate.py

See https://github.com/mozilla/glean/pull/1572

Update schema to allow for "special" glean_* pings

---

docs/index.rst

Fix RST syntax

---

.github/pull_request_template.md

Bug 1703818: Update HISTORY.rst to CHANGELOG.md

---

.circleci/config.yml

Add CircleCI job to test on Python 3.10-rc

---

CHANGELOG.md
glean_parser/javascript.py
tests/data/single_labeled.yaml
tests/test_javascript.py

Include imprt statement for labeled metric subtype in TS/JS templates

---

setup.py

[Links to CVE's for PyYAML](https://github.com/mozilla/probe-scraper/security/dependabot/requirements.txt/PyYAML/open).
I would have preferred to go all the way to 5.4.0, but m-c hasn't upgraded that far yet.

Update PyYAML to 5.3.1 for security reasons

---

glean_parser/__main__.py

Fix mypy errors with the recent click update

---

CHANGELOG.md
glean_parser/templates/swift.jinja2
tests/test_swift.py

Ensure pings are correctly generated in Swift 

---

CHANGELOG.md
glean_parser/templates/swift.jinja2

Fix return value of `ExtraKeys` protocol in Swift code

---

CONTRIBUTING.md

Bug 1706043 - Update instructions for updating glean_parser on Glean clients

---

.circleci/config.yml
CONTRIBUTING.md
Makefile
docs/installation.md

Based on #339, only the last commit is relevant.

Don't rely on setup.py for installation anymore

---

CHANGELOG.md
glean_parser/kotlin.py
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
setup.py
tests/data/core.yaml
tests/test_csharp.py
tests/test_kotlin.py
tests/test_swift.py
tests/test_translate.py

Add missing parts for new events API

---

CHANGELOG.md
glean_parser/javascript.py
glean_parser/templates/javascript.jinja2
glean_parser/templates/qmldir.jinja2
tests/test_javascript.py

Bug 1707896 - Transform generated folder into QML Module when building for Qt

---

CHANGELOG.md
glean_parser/__main__.py
glean_parser/data_review.py
glean_parser/util.py

- No tests because I'm not rightly sure how to test a big old text emit. But I did try it on glean-core metrics.yamls as well as FOG's

bug 1704541 - Add command to generate data review request

---

requirements_dev.txt

This required a few tweaks, so replaces dependabot's #348

Upgrade to mypy 0.901

---

Makefile

Add a make task to autoformat all files

---

glean_parser/data_review.py

No bug - Fix minor typo in data-review request form

---

glean_parser/parser.py
glean_parser/util.py
tests/data/all_pings.yaml

Bug 1680800 - Provide line numbers in the metrics.yaml in glean_parser error messages

---

CHANGELOG.md

So apparently I pushed that 2 weeks ago but didn't open a PR for it

Fix URLs in changelog for old release

---

CHANGELOG.md
glean_parser/javascript.py

Bug 1728982 - Add support for Node.js platform on JS / TS templates

---

CHANGELOG.md
glean_parser/templates/javascript.jinja2
tests/test_javascript.py

Friend PR for: https://github.com/mozilla/glean.js/pull/768

Bug 1702468 - Update private import paths on Javascript template

---

setup.py

Bug 1733371: Disallow jsonschema >= 4.0.0

---

CHANGELOG.md
glean_parser/kotlin.py
glean_parser/parser.py
glean_parser/util.py
setup.py
tests/test_csharp.py
tests/test_kotlin.py
tests/test_parser.py
tests/test_swift.py

(And as a side-effect, fix the unit test breakage on jsonschema 4.0.0)

Bug 1733395: Improve schema validation error messages

---

CHANGELOG.md
glean_parser/translate.py
tests/data/metric-with-tags.yaml
tests/data/tags.yaml
tests/test_translate.py

Skip tags when generating code

---

tests/data/all_metrics.yaml
tests/test_javascript.py
tests/test_kotlin.py
tests/test_swift.py
tests/test_translate.py

Add a test that contains all possible metric types at least once

---

glean_parser/lint.py
glean_parser/util.py
tests/data/bad_ping.yamlx
tests/test_cli.py

This includes YAML lints, Glean lints and schema errors.

Bug 1746054 - Always report all lints & errors when glinting

---

CHANGELOG.md
glean_parser/parser.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/metric-with-tags.yaml
tests/data/tags.yaml
tests/test_parser.py

bug 1745283 Support file-level tags

---

requirements_dev.txt

Bump coverage 6.3.1 for Python > 3.6 only

---

CHANGELOG.md
glean_parser/data_review.py

bug 1752576 - data-review knows emails, and when the list is empty

---

CONTRIBUTING.md

Fix the broken link to update glean_parser in Glean.js

---

CHANGELOG.md
glean_parser/util.py
tests/test_parser.py

Fix the expiration by version logic

---

AUTHORS.md
docs/conf.py
docs/installation.md
glean_parser/__init__.py
setup.py

Wasn't sure about Development Lead.
It for sure includes me, but also you or Bea?

Mark the Glean team as author of this package

---

CHANGELOG.md
glean_parser/templates/swift.jinja2

See commits for list of issues fixed.

Bug 1761791 - Fix issues with Swift template

---

glean_parser/data_review.py

See also https://github.com/mozilla/data-review/pull/35/files

Update data-review template

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

Bug 1798713 - events: Increase extras limit to 15

---

.circleci/config.yml

I was getting annoyed by how right-driftign this file was.
This now passes yamllint with
```
yamllint .circleci/config.yml -d '{ "extends": "default", "rules": { "line-length": { "max": 100}}}'
```
(I did not set up any automation for yamllint though)

2-space indentation only!

---

setup.py

Mark project as Production/Stable

---

.circleci/config.yml
CHANGELOG.md
glean_parser/lint.py
setup.py
tests/test_cli.py
tests/test_lint.py

Bug 1830049 - Remove direct yamllint integration

---

CHANGELOG.md
glean_parser/lint.py

Add empty function back to unbreak last version

---

CHANGELOG.md
glean_parser/lint.py

Remove `lint_yaml_files` again

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

Still needs discussion whether we _should_

Bug 1844388 - Increase short_id limit to allow longer metric names

---

glean_parser/templates/javascript_server.jinja2

* Replace a TS `any` type with a new type
* Replace a few instances of `let` (that some linters might complain about) with `const`
- I see warnings related to Python dependencies but nothing related to my changes
- As far as I can tell there are no tests for the template file I updated
- I don't think the small edits in this PR need a changelog entry

Update server-side js/ts output template

---

glean_parser/templates/javascript_server.jinja2

DENG-1320 - Add user_agent and ip_address to js server template

---

glean_parser/templates/javascript_server.jinja2

Addresses https://github.com/mozilla/fxa/pull/15659#discussion_r1284899879

Update JSDoc in server JS template

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
glean_parser/util.py
requirements_dev.txt
setup.py
tests/test_parser.py

Drop Python 3.6 support

---

CHANGELOG.md
glean_parser/lint.py
tests/test_lint.py

Bug 1859561 - Warn about empty or TODO-tagged data reviews in the list

---

CHANGELOG.md
glean_parser/templates/ruby_server.jinja2
tests/data/server_events_compare.rb

Very lightweight change to add updated Ruby logging logic
https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-894

feat(ruby): adding new logic currently in Mastodon main to parser

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

Bug 1869429 - Increase event extra key limit from 15 to 50

---

glean_parser/templates/rust.jinja2

Rust: Use re-exported serde traits from glean

---

glean_parser/templates/rust.jinja2

Rust codegen for object fixes

---

Makefile
glean_parser/go_server.py
glean_parser/javascript_server.py
glean_parser/python_server.py
glean_parser/ruby_server.py
requirements_dev.txt
setup.cfg
tools/extract_data_categories.py

Switch to ruff as linter/formatter

---

CHANGELOG.md
glean_parser/parser.py
glean_parser/pings.py
glean_parser/schemas/pings.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
tests/data/pings.yaml
tests/test_pings.py

This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1804711.

Bug 1804711 - Support a ping_schedule metadata property for pings.

---

CHANGELOG.md
Makefile
glean_parser/kotlin.py
glean_parser/pings.py
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/detekt.yml
tests/test_kotlin.py
tests/test_pings.py
tests/test_swift.py

Bug 1879828 - Object metric code gen for Kotlin & Swift

---

CHANGELOG.md
glean_parser/util.py

Bug1892055 - Fix missing ping_arg in util.py

---

glean_parser/templates/rust.jinja2

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1895230

Set a default empty array if value is missing

---

server_telemetry/sdk-metrics-compat.yaml

Fix schema identifier of internal Glean metrics

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/all_metrics.yaml

bug 1657947 - New metric types labeled_{custom|memory|timing}_distribution

---

CHANGELOG.md
glean_parser/templates/rust.jinja2

- Tested in Glean SDK (PR forthcoming)

bug 1909244 - Update rust codegen to handle LabeledMetricData

---

glean_parser/templates/kotlin.jinja2
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
tests/test_kotlin.py
tests/test_rust.py
tests/test_swift.py

Bug 1908157 - Kotlin: Generate a serializer for array wrappers

---

CHANGELOG.md
glean_parser/templates/javascript_server.jinja2
glean_parser/templates/ruby_server.jinja2
tests/data/server_events_compare.rb
tests/data/server_metrics_with_event.yaml
tests/test-py/test.py
tests/test_javascript_server.py
tests/test_ruby_server.py

Fixes https://mozilla-hub.atlassian.net/browse/DENG-4405.

Stringify event extra values in server JS template

---

README.md
glean_parser/util.py
setup.py

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067967
- I build this for Debian

replace deprecated appdirs with platformdirs

---

glean_parser/schemas/pings.2-0-0.schema.yaml

Clarify docs around disabling pings and its data

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/all_metrics.yaml

bug 1925346 - Support new metric type labeled_quantity

---

setup.py

Allow earlier versions of platformdirs

---

glean_parser/metrics.py
tests/test_parser.py

Bug 1929644 - Improve error message for missing/invalid type delcarations on an object metric

---

.circleci/config.yml

CI: Setup Rust toolchain

---

CHANGELOG.md
glean_parser/pings.py
glean_parser/schemas/pings.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
tests/data/pings.yaml

bug 1920732 - Support parsing uploader_capabilities for pings

---

glean_parser/schemas/metrics.2-0-0.schema.yaml

bug 1945840 - Correct mirroring doc link in metrics schema

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/test_parser.py

Bug 1959696 - Increase the maximum label length to 111

---

glean_parser/metrics.py
glean_parser/parser.py
glean_parser/rust.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
tests/data/all_metrics.yaml
tests/data/dual_labeled.yaml
tests/data/dual_labeled_invalid.yaml
tests/test_parser.py
tests/test_rust.py

Bug 1957085 - Adding dual labeled counter

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
pyproject.toml
uv.lock

Bug 1975519 - Bump minimum required Python version to 3.9

---

glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2

Accompanied by https://github.com/mozilla/glean/pull/3231

Bug 1983858 - implement intoSerializedObject recursively
