glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.schema.yaml

In current version of the spec, these are constants, not per-metric parameters.

Drop max_length / max_entries parameters

---

glean_parser/kotlin.py
glean_parser/templates/kotlin.jinja2.kt

As discussed [here](https://github.com/mozilla-mobile/android-components/pull/1171/files#r228514134), we should always write out every argument, even if it's set to a default value.  This lets us define the default values in a single place (`glean_parser`), rather than in multiple places throughout the glean metric code.

Always write out arguments, even if set to defaults

---

glean_parser/metrics.py
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml
tests/test_metrics.py
tests/test_parser.py

Based on discussion in https://github.com/mdboom/mobile-telemetry-sdk-schemas/pull/2, this changes the `$schema` value to be an obviously unresolvable URL, and also make it optional.  This requires some workarounds for how JSON schema is used.
There will be some required changes in `android-components`, forthcoming.

Use unresolvable URL as $schema id

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

As discussed here: https://github.com/mozilla-mobile/android-components/pull/1308#discussion_r233093823
The event metric should always have a lifetime of ping.

Enforce that event lifetime is ping

---

glean_parser/parser.py
glean_parser/translate.py
tests/data/schema-violation.yaml
tests/test_metrics.py
tests/test_parser.py
tests/util.py

When schema validation fails, in the interest of giving the user every possible error, that invalid data produces more obscure errors downstream.
This cuts things off after the schema validation errors if anything fails at that step, and only present the more specific downstream errors if validation itself passes.
This also removes the display of schema fragments when a schema validation fails.  I think those are useful for schema authors -- less useful for those trying to validate against it.  It also shows subschemas that failed, if any, on the same part of the document.
In addition, this checks the schema itself to ensure it's valid, and adds separator lines in the output to make it clear how the long schema validation messages are grouped.
@georgf

1507793, 1507794, 1507795: Improve error messages

---

glean_parser/parser.py
tests/test_parser.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1507792
@georgf

1507792: Better error message when metrics.yaml is empty

---

README.rst
glean_parser/__main__.py
glean_parser/parser.py
glean_parser/util.py
glean_parser/validate_ping.py
setup.py
tests/test_validate_ping.py

This adds a feature to glean_parser to validate pings.  It's basically a straightforward use of the `jsonschema` library that the backend uses to do that.
I've just copied the ping schema into this repo rather than doing anything fancy like fetching it from a URL because:
1. We don't want to fetch from the URL every time we run a unit test in Glean.  We could cache it, but cache invalidation is hard :cry:
2. We're already relying on changes to the ping schema that aren't yet merged into `mozilla-pipeline-schemas`.  At least until things settle down we probably want to be more nimble and have the ability to put what we need to in here.
We definitely can and should revisit that later.

Fix 1504200: Add ping validation feature to glean_parser

---

glean_parser/__main__.py
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/templates/kotlin.jinja2
glean_parser/translate.py
tests/data/core.yaml
tests/test_cli.py
tests/test_kotlin.py
tests/test_translate.py

This is the glean_parser side of the changes necessary to have a `metrics.yaml` that belongs to the glean library itself.
- Ability to (optionally) set a Kotlin namespace that the output will live in.
- Provide a default file/class name when the category name is empty.

1507743: Support namespace in output. Support default category.

---

glean_parser/metrics.py
glean_parser/templates/kotlin.jinja2
tests/test_metrics.py

Timespan and TimingDistribution both require a time_unit parameter, which is an enum users can
pick the resolution from. This adds validation for the possible values and enforces the correct code
generation.

Add a TimeUnit enum for time based metrics

---

glean_parser/translate.py
tests/data/smaller.yaml
tests/test_translate.py

This writes out all output to a temporary directory, then deletes the output directory (if any) and moves copies all contents over.  That way we should get a freshly generated tree each time.
Note that this means we must completely *own* the output directory as anything already in there will be deleted.  This fits in fine with how we currently use `glean_parser` within `android-components`, but just wanted to flag that.

Fix 1516538: Clean out old files when generating source

---

glean_parser/templates/kotlin.jinja2

This makes the generated specific metrics internal to the package they are defined in.
This relies on https://github.com/mozilla-mobile/android-components/pull/1879 so that the metrics are defined in the correct package.  Then there will also need to be a follow-on PR to android-components to update the glean_parser so that compiler will actually enforce the fact that the metrics are internal.

1523331: Make metrics internal to the package they are defined in

---

tests/test_parser.py

As mentioned [here](https://github.com/mozilla-mobile/android-components/pull/1984#discussion_r254790281) we should be extra careful that we don't get slashes into names, categories or labels.  This adds test for that at build time (it was already being checked for, but there weren't explicit tests for it).

Explicitly test for slash in names, categories and labels

---

AUTHORS.rst
glean_parser/metrics.py
tests/test_metrics.py

This is going to be used by the probe-scraper to properly identify metrics. See https://github.com/mozilla/probe-scraper/issues/67

Add Metric Identifier

---

glean_parser/templates/kotlin.jinja2

Simple fix required to generate code for the DatetimeMetricType added in https://github.com/mozilla-mobile/android-components/pull/2014.  This needs the `TimeUnit` enum.  Rather than adding all kinds of brittle logic of when to import it, just imports it always and adds a hint to `ktlint` to not complain.

1525045: Fix code generation so TimeUnit is available to DatetimeMetricType

---

glean_parser/schemas/metrics.1-0-0.schema.yaml

These parameters are already validated by the schema as being required, it just helps to make it more explicit in the docs (as is already done for the other required parameters).

Add "required" to the parameters that are required.

---

glean_parser/metrics.py
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml
tests/test_metrics.py

This ties up a couple of loose ends from the event API changes proposal.
1) It makes sure that event extra data keys starting with `glean.` are reserved for internal use.
2) It makes the entries in the extra_keys parameter an object rather than a string so we can attach other metadata in the future.
(It was easiest to handle these two bugs as a unit, since they are so closely related).

1535339, 1535341: Improvements to event extra metadata

---

glean_parser/kotlin.py
glean_parser/templates/kotlin.jinja2
glean_parser/util.py
tests/data/core.yaml
tests/test_kotlin.py

This is the glean_parser side of using `enums` for events.

1536083: Use enums for extra keys on events

---

glean_parser/templates/kotlin.jinja2

This will be tested by the corresponding PR in android-components, coming shortly.

Fix #45: NoExtraKeys should always be imported in generated code

---

glean_parser/util.py
tests/data/core.yaml
tests/data/smaller.yaml

This also fixes a bug when metrics.yaml files contain a date for expires.
PyYAML will convert those dates into datetime objects, which can't be validated
by JSON schema (which doesn't understand datetimes).  We want that always to
be strings, so we use a workaround to get PyYAML to not generate datetimes.

1539126: Don't use expires: never

---

glean_parser/templates/kotlin.jinja2

This must coincide with changes to the glean library, moving all metric types to a /metrics subdirectory.  I'll update this with the PR # from android-components as soon as it's filed.

Update template import statements to add .metrics sub-package

---

glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

This makes the following improvements to messages about errors in metrics.yaml:
- The snippet that caused the error is printed inline as YAML, rather than
Python repr (approx. JSON). This should match the input much better.
- The location of the error is now represented by adding context to the YAML
(i.e. adding the dictionary keys that lead to the location of the source
of the error).  Prior to this, this used a Pythonic syntax like
['category']['metric']
- The `description` field in the JSON schema chunk that didn't validate
is printed with the error.
- If there are missing required properties, a single error is displayed showing
all of the missing properties.  Prior to this, there was an error emitted for
each missing property.
- The filepath is displayed as an absolute path so it …

1509053: Improve glean_parser error messages

---

glean_parser/templates/kotlin.jinja2

This puts the "public-not-public" API under the namespace `private` to make that more obvious.

1540844: Rename metrics -> private

---

glean_parser/kotlin.py
glean_parser/templates/kotlin.jinja2

This is a workaround to not require Kotlin introspection.
We currently use introspection to get the string value of the extra key from the enum value.  The idea here is to not try to get the value directly from the enum, but just store a List of the strings with each event metric and use the enum's `ordinal` to look up the string in that List.

1543487: Don't use Kotlin introspection

---

glean_parser/kotlin.py
glean_parser/templates/kotlin.jinja2
tests/data/duplicate_labeled.yaml
tests/test_kotlin.py

The glean_parser side of fixing https://github.com/mozilla-mobile/android-components/issues/2793

Don't emit duplicate imports

---

glean_parser/__main__.py
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/pings.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
glean_parser/translate.py
glean_parser/util.py
tests/data/pings.yaml
tests/data/schema-violation.yaml
tests/test_kotlin.py
tests/test_metrics.py
tests/test_parser.py
tests/test_pings.py
tests/util.py

This adds support for `pings.yaml` files to `glean_parser`, in support of describing pings so that they can indicate whether they should include the `client_info` block.

1529226: Add support for pings.yaml

---

glean_parser/translate.py
tests/test_translate.py

This fixes a bug introduced a couple weeks ago with pings.yaml support was added.  The way in which the expiration parameter is turned into a disabled value was broken.  (Discovered while working on #62, but this is just the minimal bugfix).

BUG: Make sure "expires" transfers to "disabled"

---

glean_parser/metrics.py
glean_parser/translate.py
tests/test_translate.py

Currently, the translation of the special store name "default" to "metrics" or "events" is handled at runtime.  Since this is a build-time constant, we can actually deal with this in glean_parser and remove some work from the client.

1504677: Handle default stores at build-time in glean_parser

---

tests/data/core.yaml
tests/data/duplicate_labeled.yaml
tests/data/schema-violation.yaml
tests/data/smaller.yaml
tests/test_kotlin.py
tests/test_metrics.py
tests/util.py

Should be an easy review.  Just updates our "dummy" domains to "example.com" as @badboy suggested [here](https://github.com/mozilla-mobile/android-components/pull/2890#discussion_r280059610).

Use example.com as a dummy domain

---

glean_parser/kotlin.py
glean_parser/templates/kotlin.jinja2
tests/test_kotlin.py

This is needed since `glean.rs` exists in a different Kotlin namespace.

Make glean namespace configurable

---

glean_parser/schemas/pings.1-0-0.schema.yaml

It suddenly occurred to me that we have a much easier path to getting [1547967](https://bugzilla.mozilla.org/show_bug.cgi?id=1547967)
1. Define the new metadata fields, but make them optional
2. Update a-c to use this version of `glean_parser` and adding the new fields.  <-- This should not break Fenix, since the new fields are optional (https://github.com/mozilla-mobile/android-components/pull/2890)
4. Submit a PR against Fenix to add the new fields (https://github.com/mozilla-mobile/fenix/pull/2472).  This should work once the a-c snapshot is made and pulled into Fenix
5. Make these new fields required, as we want (to make sure data review is being performed and all that jazz...)
6. Update a-c to pull in the glean_parser making these fields required.  This shouldn't break Fenix because …

Make new pings metadata fields optional

---

glean_parser/parser.py
glean_parser/translate.py
tests/test_translate.py

The `send_in_pings` parameter defaults to `[metrics]` or `[events]` depending on the type of metric.  (As well, the `default` value maps to one of those).
This was only happening when generating bindings for Kotlin, but it should be happening earlier so other tools (`probe_scraper`) will also benefit from this behavior.  As it stands, the `schema-generator` currently has a bug that will cause some metrics to not show up if they don't explicitly specify the ping they are sent on.  This should resolve that (once merged and the dependency is bumped in `probe_scraper`).

Handle send_in_pings preprocessing in `parse_objects`

---

glean_parser/schemas/metrics.1-0-0.schema.yaml

This expands the regex for labeled metrics to allow for dotted snake-case.

Allow dotted snake-case for labeled metric IDs

---

glean_parser/schemas/pings.1-0-0.schema.yaml

Now that we have these fields everywhere that has a pings.yaml, let's make them officially required.  Any future custom pings will be forced to set these which is good for data stewardship.

1553186: Make pings metadata fields required.

---

glean_parser/schemas/metrics.1-0-0.schema.yaml

Related to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/338
This updates the length limit of static labels defines in metrics.yaml to 61 characters, to be consistent with the requirement for Glean's own error reporting.

1556684: Update label length

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml

This is related to mozilla-services/mozilla-pipeline-schemas#356 . It's the second part to the fix for [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1566764).

Allow for '-' in metrics labels

---

docs/metrics-yaml.rst
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.jinja2
tests/data/gecko.yaml
tests/test_kotlin.py

This adds support for the `gecko_datapoint` property in the `metrics.yaml` file for the Glean SDK.
In addition, this updates the jinja2 template to produce a function to map Gecko metrics to Glean SDK metrics and adds test coverage.
See [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1566356) and the blocked meta bug for more context.

 Enable parsing of the `gecko_datapoint` attribute in metrics.yaml 

---

CONTRIBUTING.rst
glean_parser/__init__.py
requirements_dev.txt
setup.cfg
setup.py

This moves to use `setuptools-scm` instead of `bumpversion`.  Hoping this is more robust on Windows.  It also has the advantage that versions can be tagged using the Github UI so there's no complicated commandline steps that can fail.
@Dexterp37: Would you mind testing the following on Windows?
```
python setup.py --version
```
```
python setup.py test
```

Use setuptools-scm instead of bumpversion

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

As a follow-on to #75 that I just though of -- This should prevent users from putting a `gecko_datapoint` on an unsupported metric type.

Ensure gecko_datapoint only appears on timing_distribution

---

.github/pull_request_template.md
CONTRIBUTING.rst
HISTORY.rst

Yesterday, I tagged a 1.0.0 release, and with that comes strictly using semver and keeping a good changelog.
This just adds that to the PR template, and backfills the changelog with one thing that slipped through the cracks yesterday.

Add instructions to use changelog, and backfill changelog

---

glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/test_parser.py

This just ensures that other libraries can't use the special "all_pings" value that is required for error metrics.

1569765: Add check for special case of "all_pings"

---

HISTORY.rst
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/data/pings.yaml
tests/test_markdown.py
tests/test_parser.py

See background discussion in https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/390
The only known cases of existing glean pings that do not already match this naming convention are in the [android components sync library metrics.yaml](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/storage-sync/metrics.yaml) so my main concern is understanding exactly what the upgrade path is.
If this change is merged in the glean parser, will that start failing builds for android components and/or apps using the sync library? Do we need to stage changes for that whole stack and merge concurrently with this change?
Alternately, should we bump the schema version for pings.schema.yamlto ease the transition?
- `make test` runs without emitting any …

Restrict ping names to be kebab-case

---

glean_parser/kotlin.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.geckoview.jinja2
glean_parser/templates/kotlin.jinja2
tests/data/gecko.yaml
tests/test_kotlin.py

This changes the parser to support Gecko scalars in the Glean SDK. See the related android components PR mozilla-mobile/android-components#4344 .

Add support for Gecko scalars

---

glean_parser/templates/kotlin.geckoview.jinja2

This makes sure the `when` statement doesn't get generated at all if there are no elements.

Remove warnings in the generated Kotlin template

---

glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/schema-violation.yaml
tests/test_parser.py

This additionally adds test coverage and bumps the maximum label size to 71 characters
(max category len + max name len + 1).

Bump the metric name limit to 30 characters

---

HISTORY.rst
glean_parser/kotlin.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/templates/kotlin.geckoview.jinja2
tests/data/gecko.yaml
tests/test_kotlin.py

This adds a function to look up labeled counters that will represent Gecko [categorical histograms](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/collection/histograms.html#categorical).
**Notes**
Gecko categorical histograms are a special kind of linear histograms in which bins are associated to user-provided labels: the labels can be used to increment the counts in the bins. This Gecko type naturally maps to Glean SDK `labeled_counter` with static labels. The `GleanAdapter` in A-C's engine-gecko-* will need to know when an histogram accumulation is related to a categorical histogram: in that case, the adapter will need to find the corresponding Glean SDK generated metric and attempt an accumulation with that.
**Quirks**
Gecko will only send us the value of the …

Generate a lookup table for Gecko categorical histograms

---

HISTORY.rst
glean_parser/kotlin.py
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/data/core.yaml
tests/data/duplicate_labeled.yaml
tests/data/duplicate_send_in_ping.yaml
tests/data/empty.yaml
tests/data/gecko.yaml
tests/data/invalid.yaml
tests/data/pings.yaml
tests/data/schema-violation.yaml
tests/data/smaller.yaml

This additionally adds the missing license headers. Note that this fixes mozilla/glean#321.
I attempted to write a test for this, but it is a bit hard: unless we try to compile Kotlin code, how do we know that something is missing?

Pass `memory_unit` to the MemoryDistributionMetricType in Kotlin

---

.gitignore
HISTORY.rst
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml

This removes all but the labeled_boolean, labeled_counter, and labeled_string from the "labeled" types.

1585699 - Remove unsupported labeled metric types

---

HISTORY.rst
glean_parser/templates/kotlin.jinja2

This was reported by :jnicol while working on the GeckoView integration. Both types are used to specify the properties of the generated Custom and Memory distributions instances.

Add the imports for supporting Custom and Memory distributions

---

glean_parser/markdown.py

This fixes a bustage introduced by #118: ` AttributeError: 'Ping' object has no attribute 'is_internal_metric'`

Do not check `is_internal_metric` for Pings

---

glean_parser/markdown.py
glean_parser/templates/markdown.jinja2
tests/test_markdown.py

This fixes  [Bug 1578345](https://bugzilla.mozilla.org/show_bug.cgi?id=1578345).
I am not very sure about the solution, because it looks kind of fragile. But I thought it was best to send this in and discuss with some code on the table.

Add support for labels to the Markdown template

---

glean_parser/lint.py
tests/test_lint.py

This only handles builtin pings (and doesn't do baseline, because we actually don't want more metrics in there).

Warn for slight misspellings in ping names.

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/metrics.py
tests/test_parser.py

These labels were recently changed to lists to ensure the labels
ordering from `metrics.yaml` was kept in the markdown generated
documentation. That had the unwanted effect of changing the type
of the labels in the Kotlin and Swift generated codes.
To fix this, a new property `ordered_labels` was added to the
Labeled types which is a list. Keeping the actual `labels` property
a set.
See discussion: https://github.com/mozilla-mobile/android-components/pull/4750#discussion_r336030971

Make labels from Labeled types sets again

---

.circleci/config.yml
.gitignore
CONTRIBUTING.rst
HISTORY.rst
Makefile
glean_parser/templates/kotlin.geckoview.jinja2
glean_parser/templates/kotlin.jinja2
tests/detekt.yml
tests/test_kotlin.py

This sets the stage for, but doesn't really fix [1590080](https://bugzilla.mozilla.org/show_bug.cgi?id=1590080).  This just adds `detekt` to the checks performed on the generated Kotlin code in CI, and adds the necessary supressions to make them pass.

Run detekt over generated Kotlin code in unit tests

---

HISTORY.rst
docs/metrics-yaml.rst
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/data/core.yaml
tests/test_parser.py

This is tech debt, but it will come in handy to have this cleaned-out for the Python bindings work over in glean-core.

1573191: Remove metric types that aren't implemented in glean-core

---

HISTORY.rst

We need a new release to use the yamllint in mozilla/glean

Update HISTORY.rst to prepare for v1.11.0

---

HISTORY.rst
glean_parser/kotlin.py
glean_parser/pings.py
glean_parser/schemas/pings.1-0-0.schema.yaml
glean_parser/templates/swift.jinja2
tests/test_pings.py

Added a new flag `sendIfEmpty` for pings

---

.circleci/config.yml
CONTRIBUTING.rst
HISTORY.rst
Makefile
README.rst
glean_parser/__init__.py
glean_parser/kotlin.py
glean_parser/lint.py
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/pings.py
glean_parser/swift.py
glean_parser/translate.py
glean_parser/util.py
requirements_dev_py35.txt
setup.cfg
setup.py
tests/test_cli.py
tests/test_kotlin.py
tests/test_markdown.py
tests/test_pings.py
tests/test_swift.py
tests/test_translate.py

This PR makes me :cry:
Basically, the changes are:
- Don't use `dataclasses`.  Most of the type checking it provided for us was redundant anyway, since we validate using the JSON schema before getting there anyway.
- `pathlib.Path` didn't play well with the rest of the `stdlib` in Python 3.5, so we need to do more explicit casting to strings.
- `datetime.datetime.fromisoformat()` is new in 3.7, so this uses a backport library
- `__init_subclass__` is new in 3.6, so we use the `pep487` backport library for that
- f-strings are new in 3.6, so we have to go back to `str.format()` :nauseated_face: 
- Dictionaries have a stable ordering in 3.7, so here we have to use `OrderedDict` in a number of places to make the tests pass consistently.
And, of course, this also adds CI for Python 3.5 and …

WIP: 1600257: Support Python 3.5

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/parser.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
glean_parser/schemas/pings.1-0-0.schema.yaml
tests/data/pings.yaml
tests/test_markdown.py
tests/test_parser.py
tests/test_pings.py

This supersedes #90 and #94, and adds special cases to
allow current legacy ping names with underscores to continue
to work.

Bug 1601270 Restrict ping names to be kebab-case

---

README.rst
glean_parser/__init__.py
glean_parser/util.py
setup.py

The reasons for this PR are a bit obscure.
We were using the `backports.datetime_fromisoformat` library to support parsing iso8601 dates on Python 3.6 and earlier (where such functionality is not in the standard library).  However, this library includes a C extension, so installing it on Windows requires a C compiler to be handy and installed correctly so Python can find it (which is not always the case, even if the user otherwise has their machine set up for C/C++ development).
This replaces that library with another one that is pure Python to avoid this issue.

Use iso8601 library rather than backports-fromisoformat

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/templates/markdown.jinja2

Fixes [Bug 1578347](https://bugzilla.mozilla.org/show_bug.cgi?id=1578347)
...and as a bonus fixes [Bug 1586730](https://bugzilla.mozilla.org/show_bug.cgi?id=1586730), about removing "Sorry about that" from the markdown template. I just remembered that bug and it was easy enough to remove that line. I can revert that commit if this is a problem :)

Add project title to the markdown template

---

.circleci/config.yml

This should prevent against future errors like #148 where we inadvertently added a dependency that requires a C compiler at install time.  We can't count on a working C compiler to be available every where that glean_parser is used, so we should detect when we use a dependency like that and break the build.
(NOTE: I expect this PR to fail the first time as a way of testing it, and then will come back and remove the "bad" dependency to make it pass.)

Break the CI build if any of the dependencies require a C compiler

---

HISTORY.rst
glean_parser/swift.py
glean_parser/templates/swift.jinja2
tests/test_swift.py

This fixes 2 small bugs (one is a drive-by fix).
Caution: mozilla/glean will still not compile with this, due to the reason code changes, that don't exist yet for Swift.

1611111 - Restore the order of extra arguments in Swift code

---

HISTORY.rst
glean_parser/swift.py
glean_parser/templates/swift.jinja2
glean_parser/translate.py
tests/test_swift.py

Prior to this, it was never generating "import Glean", which broke builds of
third-party Glean-using products.

Swift: Generate "import Glean" based on allow_reserved flag

---

HISTORY.rst
setup.py

I created a branch `release-v1.15` based on the `v1.15.5` tag.
This PR is against that branch, backporting the single-line fix from v1.17.3.
Once this lands and is tagged I'm going to merge the changelog changes into master as well in a follow-up PR.

Specify maximum version of Jinja2 (backported from v1.17.3)

---

CONTRIBUTING.rst

Maybe some day we'll want to pull over the detailed gitflow instructions from glean itself, but this at least does the minimal changes to mention using GitHub releases.

Update deploy instructions to mention using GitHub releases

---

HISTORY.rst
glean_parser/templates/kotlin.jinja2

Related to [Bug 1588060](https://bugzilla.mozilla.org/show_bug.cgi?id=1588060).
When this lands and glean is updated, it should also include tests for the Java API in https://github.com/mozilla/glean/blob/master/glean-core/android/src/test/java/mozilla/telemetry/glean/GleanFromJavaTest.java.

Have the metrics names in Java match their names in Kotlin

---

glean_parser/templates/kotlin.jinja2

This fixes a bug introduced in #165, where @JvmName isn't allowed on private
members, and results in this compiler error:
w: glean-core/android/build/generated/source/glean/debug/kotlin/GleanError.kt: (97, 5): An accessor will not be generated for 'invalidOverflowLabel', so the annotation wil
l not be written to the class file

Fix @JvmName annotation on private members

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/templates/markdown.jinja2

This fixes a couple of bugs introduced in #170.
- Even built-in pings should have their reason codes listed
- Properly indent the output so the markdown list is rendered correctly

Fixes bugs in markdown reason support

---

HISTORY.rst
README.rst
glean_parser/util.py
setup.py
tests/test_utils.py

This is required in order to integrate in mozilla-central, [see this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1602773).
Given :ahal comment on the bug, I checked about downgrading pyYAML to 3.11. However 3.13 contains [fixes for python 3.7](https://github.com/yaml/pyyaml/blob/2f463cf5b0e98a52bc20e348d1e69761bf263b86/CHANGES#L83), which we need to support. I'll attempt to update pyyaml in m-c.

Drop 'inflection' and make transitive dependencies versions explicit

---

HISTORY.rst
glean_parser/translate.py
tests/test_translate.py

This is just a minor refactor to create an entry point where another glean_parser-using-library can provide their own translation function.  It doesn't provide a *ton* of value over what could be done without this change except providing access to the transactional directory writing behavior.

1618873: Support external translators

---

HISTORY.rst
docs/metrics-yaml.rst
glean_parser/lint.py
glean_parser/util.py
glean_parser/validate_ping.py
setup.py
tests/test_cli.py

On 32-bit Windows with the upstream python.org interpreter, the default encoding for loading files is locale-dependent (and is cp1252 in en_US, for example). This breaks when trying to load a `.yaml` file in UTF-8.
This fixes things by always treating files as `UTF-8`.  This is strictly not 100% YAML-compliant, which says YAML can be in UTF-8 or UTF-16 if a BOM is present.  However, the `yamllint` library doesn't provide a way to automatically determine the encoding -- it requires that its input as already decoded.  In practice, I don't think this is much of an issue: UTF-8 is the most sane choice in 2020 and we can just document that requirement.
For JSON files, the JSON standard *requires* it to be UTF-8 anyway, so we are now simply correct there.
- `make test` runs without emitting any …

1622909: Fix encoding when reading in files on 32-bit Windows

---

HISTORY.rst
glean_parser/lint.py
tests/test_lint.py

Produces a warning when 'user' lifetime metrics are set to expire

---

HISTORY.rst
glean_parser/lint.py
glean_parser/translate.py
tests/test_lint.py

Also breaks out the concept of glinter warnings and errors so we can
add checks that don't break the build in the future.

Bug 1589635: Treat linter warnings as errors in translate command.

---

.circleci/config.yml
HISTORY.rst
glean_parser/util.py
setup.py

This lowers the minimum versions of dependencies as far as we can without breaking our unit tests.  Then it adds this to CI to make sure we don't start using newer APIs accidentally without updating the minimum versions.  (The third-party "requirements-builder" tool is used to help with this process).
This is a prerequisite to doing the same thing in Glean SDK.
This shouldn't have any bearing on the vendoring in m-c.

Bug 1631078: Loosen minimum versions of dependencies and test them in CI

---

HISTORY.rst
setup.py

This is a follow-on to #184 to improve the dependency specifications even further using a syntax that was rather hard to find: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies
This means we can specify the maximum version of packages *only* for when it matters (on Python 3.5), and specify the backport compatibility libraries to *only* be required when needed on older versions of Python.
This should also help with making glean_parser dependencies more broadly compatible with more environments that it may be installed into, because more recent versions of things will be considered "compatible with glean_parser" on more recent versions of Python. …

Bug 1631078: More fine-grained version control

---

HISTORY.rst
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

Bug 1640997: Use time_unit to control min and max range

---

tests/data/invalid-ping-names.yaml
tests/test_parser.py
tests/test_swift.py

Bug 1635754 - Explicitly test that underscores in ping names are disallowed

---

HISTORY.rst
glean_parser/lint.py

Bug 1638293: Make glinter messages more actionable

---

HISTORY.rst
glean_parser/metrics.py

The value of `user` and `application` were not matching the ones in mozilla/glean used for the Python bindings, causing all the metrics with "lifetime: application" to be sent as "lifetime: user".

Reorder the values of the `Lifetime` enum

---

HISTORY.rst
Makefile
glean_parser/markdown.py
tests/data/send_if_empty_with_metrics.yaml
tests/test_markdown.py

Bug 1648696 - Look for metrics in send_if_empty pings

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/schemas/metrics.1-0-0.schema.yaml

* Create JweMetric objects from Swift, Kotlin and C#;
* Display JWE metrics in markdown with `decrypted_name` as an extra.

Bug 1650787 - Support JWE metric types

---

HISTORY.rst
glean_parser/csharp.py
glean_parser/kotlin.py
glean_parser/swift.py
glean_parser/util.py

This also detected a bug that `memory_unit` was missing from the Swift
generator.
Fortunately none of our iOS seem to be using MemoryDistribution yet.

Bug 1652471: Unify the extra_args values in the generator

---

HISTORY.rst
glean_parser/csharp.py
glean_parser/templates/csharp.jinja2
tests/test_csharp.py

Without this events and static labels for labeled types would fail to compile.

Add support for HashSet and Dictionary in the C# template

---

glean_parser/templates/markdown.jinja2

This documentation might be misunderstood as enumerating _all_ the data being collected by this project. In e.g. Firefox Desktop there is (and will for the foreseeable future continue to be) quite a lot of other data being collected by other means, so we should be specific here.
No Changelog needed because it's a pedantic change to autodocs only.

Be more specific about what the autodocs documents

---

HISTORY.rst
glean_parser/lint.py
tests/test_lint.py

Bug 1599764: Warn about expired metrics

---

HISTORY.rst
glean_parser/markdown.py
glean_parser/schemas/metrics.1-0-0.schema.yaml
tests/test_parser.py

Bug 1658349 - Allow using the quantity metric type outside of Gecko

---

glean_parser/__main__.py
setup.py

Bug 1664889: Display glean_parser version when there is an error

---

HISTORY.rst
glean_parser/util.py
tests/test_kotlin.py

Bug 1666192 - Ensure kotlin arguments are deterministically ordered

---

HISTORY.rst
glean_parser/lint.py

Bug 1675771: Redirect linter output correctly

---

setup.cfg

We are using a deprecated configuration parameter to pytest that is no longer necessary.
This fixes the following warning:
```
site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: collect_ignore
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

Fix pytest warning

---

docs/installation.rst

TIL the `git` protocol is fundamentally insecure, so should probably not recommend it.  (I think this doc actually comes from a cookiecutter template -- that should probably be patched upstream, too).

Recommend https over git for cloning

---

CHANGELOG.md
glean_parser/javascript.py
glean_parser/templates/javascript.jinja2

Have also tested this in the sample Glean.js webextension and it worked. This time I tested with the published @mozilla/glean package.
Sample generated file for reference:
```js
/* eslint-disable */
/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/. */
"use strict";
// AUTOGENERATED BY glean_parser.  DO NOT EDIT.
// Global variable to use when in Qt/QML environments,
// where do not have access to the global object (i.e. window);
var pings;
// Universal Module Definition (UMD) …
```

Bug 1693323 - Leverage glean_namespace to specify glean environment in JS

---

glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/telemetry_mirror.yaml
tests/test_parser.py

- [ x] **Quality**: This PR builds and tests run cleanly
- [x ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x ] **Changelog**: This PR includes a changelog entry to `HISTORY.rst` or an explanation of why it does not need one

bug 1685406 - Add telemetry_mirror optional field to metrics schema

---

setup.py

Our README on PyPI isn't currently rendering correctly.  We need to tell PyPI it's in markdown, not reStructuredText.
https://pypi.org/project/glean-parser/

Mark long description as being in markdown

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/translate.py
glean_parser/util.py
tests/data/rate.yaml
tests/test_parser.py
tests/test_translate.py

Adds three new metric object model types:
* "rate" for rates that own both their numerator and denominator
* "numerator" for rates that have an external denominator
* "denominator" for counters that are external denominators

bug 1645166 - Add support for `rate` metrics

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml

bug 1702263 - Raise limit on statically-defined labels to 100

---

.circleci/config.yml

Addresses this message:
```
WARNING: --use-feature=2020-resolver no longer has any effect, since it is now
the default dependency resolver in pip. This will become an error in pip 21.0.
```

Remove `--use-feature=2020-resolver` flag

---

CHANGELOG.md
glean_parser/markdown.py
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/jwe.yaml
tests/test_cli.py
tests/test_metrics.py

I _think_ modifying the schema here is fine. I did that to provide an explicit error message. Does anyone else depend on this schema directly?

Bug 1700991 - Remove support for the JWE metric type

---

CHANGELOG.md
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/data/events_with_types.yaml
tests/test_kotlin.py
tests/test_swift.py

When a metric of `type: event` includes any `type` annotation in its
extra keys list, the new object/struct-based API will be used.
Only three types are supported right now:
* string
* boolean
* quantity (an integer)
This is only implemented for Kotlin & Swift.
Python will need this in the Glean Python code base.
Glean.js will need its own implementation first.
FOG will need to implement something similar for its Rust, C++ and
JavaScript API.
---
Needs to land so that Glean can use it here: https://github.com/mozilla/glean/pull/1603

Bug 1693486 - Generate new event API construct

---

CHANGELOG.md
glean_parser/kotlin.py
tests/test_cli.py

Bug 1713084 - For Kotlin only generate `GleanBuildInfo.kt` when explicitly requested

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/util.py
tests/test_parser.py

Rust doesn't have named arguments, so we need to ensure they are in
order.

Bug 1713398 - Enable custom distribution without a gecko_datapoint 

---

CHANGELOG.md
glean_parser/lint.py
tests/data/pings.yaml
tests/test_lint.py

make lint fails with error that says "would reformat glean_parser/lint.py"
Haven't made the tests, but creating a PR to look for feedback on my code

Bug 1703577 - Check for redundant words in ping names

---

.circleci/config.yml
Makefile

This makes the tests run regardless of lint failures.
Not all lint failures will lead to test failures.
This way those test failures will show up quicker.### Pull Request checklist ###

Separate linting into its own step

---

glean_parser/util.py
setup.py
tests/test_parser.py

It was a simpler version of that anyway and now got replaced.
See https://github.com/Julian/jsonschema/commit/b0be7bf48e6554a00296307f7c84283a77738267
We should be jsonschema v4 compatible now.

Bug 1713314 - Replace jsonschema's indent utility with textwrap

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml

Bug 1719315 - Add support for the URL metric type

---

CHANGELOG.md
glean_parser/javascript.py
glean_parser/templates/javascript.jinja2
tests/test_javascript.py

**JavaScript**: 
```js
...
/**
* This is another custom ping
*
* Generated from `custom-ping-might-be-empty`.
*/
export const customPingMightBeEmpty = new PingType({
includeClientId: true,
sendIfEmpty: true,
name: "custom-ping-might-be-empty",
reasonCodes: ["serious", "silly"],
});
export const customPingMightBeEmptyReasonCodes = {
"Serious": "serious",
"Silly": "silly",
}
```
**TypeScript**:
```ts
...
/**
* This is another custom ping
*
* Generated from `custom-ping-might-be-empty`.
*/
export const customPingMightBeEmpty = new PingType({
includeClientId: true,
sendIfEmpty: true,
name: "custom-ping-might-be-empty",
reasonCodes: ["serious", "silly"],
});
/**
* Reason codes for `custom-ping-might-be-empty`.
*
* @readonly
* @enum {string}
*/
export enum CustomPingMightBeEmptyReasonCodes { …
```

Bug 1719136 - Expose ping reasons enum on JS/TS templates

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/text.yaml
tests/data/text_invalid.yaml
tests/test_parser.py

This applies the following additional restrictions:
1) Metrics of this type will need to be data collection category 3 or 4.
2) Metrics of this type will only be allowed for custom pings. Sending a text metric in built-in pings is forbidden.
3) Metrics of this type will only be allowed to have a ping or application lifetime. Other lifetimes will be forbidden.
Restrictions are applied through the jsonschema.
This leads to okayish error messages for 1) and 3)
and a suboptimal, but understandable error message for 2).
---
See this output:
```
❯ python -m glean_parser -- translate --output tmp --format kotlin tests/data/text_invalid.yaml
==============================================================================
/Users/jer/mozilla/src/glean_parser/tests/data/text_invalid.yaml:
``` …

Bug 1726326 - Add support for the text metric type

---

CHANGELOG.md
glean_parser/pings.py
tests/test_pings.py

It can't be used as a ping name, but it can be used in `send_in_pings`.

Reserve the `default` ping name

---

glean_parser/util.py

`yaml_load` does some extra work, such as adding the `defined_in` metadata.
We need to replicate this for data snippets used in tests. The easiest
is to just roundtrip through `yaml.dump`.
---
Necessary for #375 to work!

In test mode dump snippets to yaml and load them again

---

.circleci/config.yml
CHANGELOG.md
setup.py

This also updates the docker images used to the [actively maintained ones](https://circleci.com/developer/images/image/cimg/python).  I don't know what the difference between these and the legacy images are, but Python 3.10 is only available in the new ones.

Support Python 3.10

---

docs/index.rst
docs/tags-yaml.rst
glean_parser/__main__.py
glean_parser/kotlin.py
glean_parser/lint.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/pings.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/schemas/pings.2-0-0.schema.yaml
glean_parser/schemas/tags.1-0-0.schema.yaml
glean_parser/swift.py
glean_parser/tags.py
tests/data/metric-with-tags.yaml
tests/test_lint.py
tests/test_parser.py
tests/test_tags.py

How it works:
* You can specify a `tags.yaml` file, which has a list of tag names
along with a description key (very similar to `pings.yaml`, but
simpler)
* Metrics and pings now have an optional `metadata` section, in which tags can
be specified as a list of strings (e.g. metadata -> tags -> ["apple",
"banana"])
* You can force tags to be defined by passing `--require-tags` to either the translator or the linter.
Still to-do:

Bug 1734011 - Support tags in glean parser

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/wrong_key.yamlx
tests/test_cli.py

The time metric types use `time_unit`, not `unit`.
Easy mistake to made, we can catch that.
Note: `time_unit` is OPTIONAL for all three metric types.
This is not a problem for `memory_distribution`, because its
`memory_unit` is REQUIRED.

Reject files if they use `unit` by mistake

---

CHANGELOG.md
glean_parser/kotlin.py
glean_parser/swift.py
glean_parser/templates/kotlin.buildinfo.jinja2
glean_parser/templates/swift.jinja2
glean_parser/util.py
tests/test_cli.py
tests/test_kotlin.py
tests/test_swift.py

Implementation of the build date field in `build info`.
Will require Glean updates as well.
---
~~Draft until proposal is formally accepted.~~

Bug 1742448 - Generate build date at invocation time

---

CHANGELOG.md
glean_parser/translate.py
tests/test_cli.py

~~This can be for 2 reasons: no files passed or empty files passed.~~
~~Both cases are actually acceptable use of Glean:~~
~~You might want to use Glean _only_ for the baseline ping.~~
~~Especially initially, when you don't have metrics.~~
~~We still need to generate the build info so users can call~~
~~Glean.initialize with valid values.~~

Bug 1751730 - Skip message if no metrics are found

---

CHANGELOG.md
glean_parser/__main__.py
glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/util.py
tests/data/mixed-expirations.yaml
tests/test_lint.py
tests/test_parser.py

This introduces a new command line argument that allows the integrator to provide the major version number of the product.
If that's provided, glean_parse will only allow metrics to expire by major version instead than date.
@mdboom do you think we should bump the schema version? This feels a pretty safe change (famous last words), as we are increasing the set of allowed values instead of restricting more.

Bug 1753194 - add support for expiring metrics by major version

---

setup.py

The new 2.1.0 release of MarkupSafe contains a breaking change (removal
of a deprecated function).
This breaks jinja2 down the line (for its 2.10 version).
The only way to fix that right now is to use the previous release.
Release notes: https://github.com/pallets/markupsafe/blob/73da17aa9cb4139b7192e859e7ca563fa299d907/CHANGES.rst
Note: The minimal jinja2 version we depend on is probably EOL, but
updating that might be a bigger change.
---
Fixes CI failures.

Fix MarkupSafe dependency to previous version

---

CHANGELOG.md
glean_parser/templates/swift.jinja2

Reverts mozilla/glean_parser#469
These changes ended up being unnecessary. They change the way to access pings and break the template when pings have reasons. Other workarounds can be used to access metrics that are module private, such as having a different Metrics.swift file per module.

Revert "Bug 1761791 - Fix issues with Swift template"

---

glean_parser/__main__.py
glean_parser/translation_options.py

@badboy ~tests seem to be failing locally for me; but they arent in any files I've changed~ chmod to the rescue
also the way I handled this is that if you use the --list-options flag ala
`glean_parser translate --list-options`
it will show a paged view of them and then exit. This has the nicety of avoiding having to set a language target (which is normally required), however this is just how it makes sense to me. I could change this implementation to work as
`glean_parser translate -o output_loc/ -f lang --list-options`
it would show you only the options for that language.  Im open to suggestion as to which is more ergonomic.

[Bug 1749471] List options accepted by each translation target in glean_parser

---

CHANGELOG.md
glean_parser/rust.py
glean_parser/templates/rust.jinja2

Adds missing `extra_args` to the constructor parameter list for things with TimeUnits, MemoryUnits, etc...

[Bug 1765855] Glean parser missing extra args in Rust constructor generation

---

requirements_dev.txt

m2r's last use was removed in 9ffcfdac4e2e003875fa0d863ef66bd16844bb0e.
watchdog was never used, it was brought in by the cookiecutter template.

Remove unused dependencies

---

CHANGELOG.md
glean_parser/javascript.py
glean_parser/kotlin.py
glean_parser/metrics.py
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
glean_parser/translate.py
glean_parser/translation_options.py
glean_parser/util.py
tests/test_javascript.py
tests/test_kotlin.py
tests/test_metrics.py
tests/test_swift.py
tests/test_translate.py

The new UniFFI-powered API changes some things:
Metric constructors now always take a `CommonMetricData` object as the first argument.
Additional type-specific arguments come after that.
This also includes the fix for [bug 1720494](https://bugzilla.mozilla.org/show_bug.cgi?id=1720494).

Bug 1769225 - Generate Kotlin/Swift code for the new UniFFI-generated API

---

setup.py

Upgraded to 2.0.1 in 644c8493170eb7fb44501a629ace5ffe3fbf1c8a,
but m-c requires 1.1.1.
That works for us so we can just allow it.

Relax version requirement for MarkupSafe

---

CHANGELOG.md
glean_parser/data_review.py

Tested manually on events with and without extra keys.
Uses data sensitivity and bug link from the parent event metric.

bug 1767027 - [data-review] Add rows to data review metric table to describe extra keys

---

glean_parser/templates/rust.jinja2

Generate new UniFFI-compatible interface for event keys

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml

bug 1772163 - Raise limit on number of statically-defined labels to 4096

---

glean_parser/templates/rust.jinja2
tests/test_rust.py

That way consumers don't need to also depend on the right version of
`once_cell`
See https://github.com/mozilla/glean/pull/2085

Rust: Use re-exported `Lazy`

---

setup.py

Later versions dropped Python 3.6 support.

Pick setuptools-scm <7 for Python 3.6

---

Makefile
pytest.ini
tests/conftest.py
tests/test_validate_ping.py

CI will by default run it, but a simple `pytest` will skip it.

Bug 1741668 - Mark test_validate_ping as requiring a web connection

---

CHANGELOG.md
glean_parser/data_review.py
glean_parser/templates/data_review.jinja2

There are a variety of unused hooks in the template to allow for easier
extension e.g. by perf-data-review in Firefox Desktop.

bug 1772605 - Use a template for glean_parser data-review

---

glean_parser/templates/rust.jinja2

Been getting the following error:
```
171 |     pub static purchase_ack_failed: ::glean::private::__export::Lazy<EventMetric<NoExtraKeys>> = ::glean::private::__export::Lazy::new(|| {
|                                                                                  ^^^^^^^^^^^
|
::: /home/brizental/.cargo/registry/src/github.com-1ecc6299db9ec823/glean-core-51.1.0/src/traits/event.rs:22:1
|
22  | pub trait ExtraKeys {
| ------------------- similarly named trait `ExtraKeys` defined here
|
help: a trait with a similar name exists
|
171 |     pub static purchase_ack_failed: ::glean::private::__export::Lazy<EventMetric<ExtraKeys>> = ::glean::private::__export::Lazy::new(|| {
|                                                                                  ~~~~~~~~~
help: consider importing …
```

BUGFIX: Add NoExtraKeys import to rust template

---

CHANGELOG.md
glean_parser/parser.py
tests/test_parser.py
tests/util.py

when list order is not deterministic, probe scraper may think a metric definition changed, and fail to merge equivalent entries in metric history.

Make tag and no_lint order deterministic

---

CHANGELOG.md
glean_parser/javascript.py
glean_parser/translation_options.py
tests/test_javascript.py

When trying to upgrade the version of `glean_parser` that Glean.js is using, we were seeing errors that the `rate` metric was not supported. The `rate` metric already exists in Glean.js and works in previous versions, but the newer versions of `glean_parser` did not support the `rate` metric for JS.
This PR
- Updates the javascript parser to correctly serialize the `rate` metric
- Removes the code that was throwing `rate` errors and skipping `rate` metrics for Glean.js (https://github.com/mozilla/glean_parser/commit/19a14a7604aaae9e8cfca83daed9e021ce10ec70)
Testing Glean.js with different versions of `glean_parser`
- 5.1.0 (current version used by glean.js) - rate works fine
- 6.2.0 (latest version) - tests fail, error saying `rate` metric is unsupported
- this branch - rate works fine, …

Bug 1793777 - Support rate metric for Glean.js/JavaScript

---

glean_parser/rust.py

Correctly serialize `Rate`s as documented into `CommonMetricData`

---

glean_parser/metrics.py
glean_parser/rust.py

Based on #533 and work for https://github.com/mozilla/glean/pull/2272.
It would be nice to have that land when we land 2272 as well, but it's not necessary. The old way still works and FOG does its own thing anyway (though it can do it better with this).
This allows us to generate non-generic code to turn strings into the correct type.

Rust: Wrap labels in Cow

---

glean_parser/metrics.py
glean_parser/rust.py

Don't `Label` prefix the inner type of a labeled metric

---

CHANGELOG.md
glean_parser/templates/kotlin.jinja2
tests/test_kotlin.py
tests/test_swift.py

Bug 1811888 - Kotlin: Generate plain enums for ping reason codes

---

CHANGELOG.md
glean_parser/kotlin.py
glean_parser/lint.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/rust.py
glean_parser/swift.py
glean_parser/templates/kotlin.jinja2
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
tests/data/core.yaml
tests/data/event_key_ordering.yaml
tests/data/events_with_types.yaml
tests/data/old_event_api.yamlx
tests/data/schema-violation.yaml
tests/test_javascript.py
tests/test_kotlin.py
tests/test_lint.py
tests/test_markdown.py
tests/test_metrics.py
tests/test_parser.py
tests/test_rust.py
tests/test_swift.py
tests/test_translate.py

For https://github.com/mozilla/glean/pull/2346
Based on #551 
---
Can't just change it in the schema because that would be breaking.
I still need to check if this breaks anything in probe-scraper. I guess it would break because we can't parse old files anymore?
In that case we would need to bump the schema to 3-0-0 and migrate all users eventually.

Bug 1811857 - Fully remove support for the old events API

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/test_parser.py

Brings it in line with dynamic labels in mozilla/glean#2364

bug 1672273 - Loosen label restrictions to 'at most 71 characters of printable ASCII'

---

CHANGELOG.md
glean_parser/parser.py
tests/data/ordering.yaml
tests/test_parser.py
tests/test_translate.py

Here's a take on making sure we have a deterministic order from `glean_parser`.
Ordered Dict is a weird one. It preserves insertion order, true, but in doing some research it's had rather a lot of changes recently and performance hasn't always been great. While this isn't a perf critical application, this method (calling sort on the `.items()` iterator) is stable, runs once each for Metrics/Pings and Tags, and will always result in a consistent order (alphabetical).
Interestingly, regular `dict` ordering is _supposed_ to be guaranteed as of 3.6, except that it's unsettled what that order should be. 

Bug 1820648 - Sort generated Metrics, Pings and Tags

---

CHANGELOG.md
glean_parser/lint.py
tests/data/unknown_ping_used.yaml
tests/test_lint.py

This introduces a new category of checks: those that run across both pings and metrics and can thus apply cross-checks.
Todo:

Bug 1833393 - New lint: check that all referenced pings are known

---

glean_parser/metrics.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/text.yaml
tests/test_parser.py
tools/extract_data_categories.py

This is the newer name. Adjusted the text as well.
---
`stored_content` is short, but is missing the `& Communications` part of the category.
but `stored_content_communications` felt so wordy.
:chutten, wdyt?

Bug 1834596 - Add `stored_content` as an alias for Cat 3 data

---

setup.py

We added that a while ago because MarkupSafe 2.1 dropped Python 3.6 support and m-c required <2.
Therefore this restriction gaves us a range of versions to work with.
Since then we dropped Python 3.6 support anyway. And hopefully this should work in m-c too.

Bug 1848902 - Drop MarkupSafe dependency version restriction

---

CHANGELOG.md
glean_parser/pings.py
glean_parser/schemas/pings.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
glean_parser/util.py

Bug 1827852 - Allow metadata to configure precise timestamps

---

Makefile

sha256sum is not available by default on macOS, but shasum is.

chore: Use shasum with algorithm selection instead of sha256sum

---

glean_parser/lint.py
tests/test_lint.py

Bug 1851999 - Prevent `ping` lifetime metrics on the `events` ping

---

CHANGELOG.md
glean_parser/metrics.py
tests/test_parser.py

This is implemented the same way time_unit is implemented for others: The specific metric class takes the argument, not the generic one.
Because the schema enforces `unit` to be required for `quantity` we can just `pop` it with the guarantee it's there.
The error message for other metrics if they do set `unit` is less nice:
Metric.__init__() got an unexpected keyword argument 'unit'
But that's in line with what `time_unit` also does.
---
~~10 minute explore of what it takes.~~
~~Needs a changelog entry and probably an additional test to cover it. I'd appreciate if someone is taking this off my hands.~~

Bug 1855046 - Allow unit only for the quantity metric

---

CHANGELOG.md
glean_parser/metrics.py
tests/test_parser.py

We specifically document that this field should be used for documentation purposes.

Allow `unit` field for custom distribution again

---

CHANGELOG.md
glean_parser/lint.py
glean_parser/metrics.py
tests/test_parser.py

Allow but warn on `unit` on a string metric

---

CHANGELOG.md
glean_parser/lint.py
glean_parser/metrics.py
tests/test_lint.py
tests/test_metrics.py
tests/test_parser.py

This partially reverts #630 (and subsequent fixes) and should unblock all failures in probe-scraper and co.

Turn a `unit` field on metrics into a warning for most metrics

---

.circleci/config.yml
Makefile
tests/conftest.py
tests/test-js/package.json
tests/test-js/test.js.tmpl
tests/test-rb/test.rb.tmpl
tests/test_javascript_server.py
tests/test_ruby_server.py

This is what I had in mind for testing the JavaScript server part behaves as expected.
It runs an actual script using `node`, logging to stdout and checking that output against the schema.

Bug 1857924 - Add an integration-like test for the javascript_server logger

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
requirements_dev.txt
setup.py

mach is dropping it too: https://bugzilla.mozilla.org/show_bug.cgi?id=1843209

Drop support for Python 3.7

---

glean_parser/__main__.py

click.argument doesn't have a way to directly document arguments. They refer to using their name directly in the help text instead. See https://click.palletsprojects.com/en/7.x/documentation/#documenting-arguments
[doc only]

Bug 1762860 - Python: Make arguments more clear in the help text

---

CHANGELOG.md
glean_parser/templates/javascript_server.jinja2

In the process of understanding how server implementations worked, I was creating my own metrics.yaml and pings.yaml configurations and noticed that the javascript_server output included "identifiers_fxa_account_id" even though that was not defined in my metrics.yaml.
Digging into the template, I realized that the other metrics that I did define were parameters on the methods for the event type metrics I had defined, but they were not passed into the record call.

fix javascript server template to include defined metrics in the parameter list for named event record calls

---

tests/test_cli.py
tests/test_go_server.py
tests/test_javascript.py
tests/test_javascript_server.py
tests/test_kotlin.py
tests/test_lint.py
tests/test_markdown.py
tests/test_ruby_server.py
tests/test_rust.py
tests/test_swift.py
tests/test_translate.py

See https://docs.pytest.org/en/7.4.x/how-to/tmp_path.html#tmpdir-and-tmpdir-factory

Replace all uses of `tmpdir` in tests with modern `tmp_path`

---

CHANGELOG.md
glean_parser/metrics.py
glean_parser/rust.py
glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
tests/data/object.yaml
tests/test_parser.py
tests/test_rust.py

This is the most bare-bones version for now.
It validates the `structure` and then generates the corresponding Rust code.

Bug 1839640 - Add new metric type: object

---

glean_parser/util.py

It is significantly faster than the Python parser. It saves more than 25% of the execution time when running the `run_glean_parser.py gifft_map` script in the Firefox codebase.

Bug 1886479 - Eventually use CSafeLoader as yaml loader

---

server-side-pings.yaml

will be included in https://github.com/mozilla/probe-scraper/pull/717 then

Bug 1874935 - Add definition of the `events` ping for server-side Glean

---

CHANGELOG.md
glean_parser/pings.py
glean_parser/schemas/pings.2-0-0.schema.yaml
glean_parser/templates/rust.jinja2
glean_parser/templates/swift.jinja2
glean_parser/util.py
tests/data/pings.yaml
tests/test_pings.py

This is enabled initially for Swift, Kotlin, and Rust

Bug 1889114 - Add 'enabled' property to pings

---

CHANGELOG.md
glean_parser/javascript_server.py
glean_parser/templates/javascript_server.jinja2
tests/test_javascript_server.py

This allows JS outputter to support pings-as-events and event metric types in a single run.
We need this to switch FxA to the latter approach.

DENG-2407 Update javascript server outputter to support mixed-style collection

---

glean_parser/__init__.py
glean_parser/util.py
requirements_dev.txt
tests/test_metrics.py

importlib.metadata is available since Python 3.8, the minimum Python we support.### Pull Request checklist ###

Use importlib.metadata instead of deprecated pkg_resources

---

server_telemetry/sdk-metrics-compat.yaml

See Option 2 in https://bugzilla.mozilla.org/show_bug.cgi?id=1874935#c16

Bug 1874935 - Send internal server metrics only in events ping

---

glean_parser/templates/kotlin.jinja2
glean_parser/templates/swift.jinja2
tests/test_kotlin.py
tests/test_swift.py

This is the patch that will make https://github.com/mozilla/glean/pull/2895 work

Object metric: Generate typealias for top-level items

---

CHANGELOG.md
glean_parser/javascript_server.py
glean_parser/templates/javascript_server.jinja2

Unfortunately some nodejs services still need to use CommonJS.  This patch adds an `-f` option to generate JS in the CommonJS module format.
- I didn't see any existing tests for the javascript_server outputter that tests individual -f options...?

Add the `commonjs_server` option to the javascript_server outputter

---

CHANGELOG.md
glean_parser/schemas/metrics.2-0-0.schema.yaml
tests/data/all_metrics.yaml
tests/data/event_key_ordering.yaml
tests/test_javascript.py
tests/test_kotlin.py
tests/test_markdown.py
tests/test_swift.py

I do not believe this to be a breaking change as it is backwards-compatible.

bug 1910976 - Expand acceptable extra_keys property names to printable ASCII (from dotted.snake_case)

---

CHANGELOG.md
glean_parser/templates/rust.jinja2

bug 1911165 - Fix rust codegen for typed extras

---

CHANGELOG.md
glean_parser/templates/kotlin.geckoview.jinja2
tests/test_kotlin.py

Now that Glean v60.4.0 has released and `service-glean` android-component has been removed, we can update the Kotlin template to use the glean import of `HistogramBase` which will allow us to do away with the `HistogramMetricBase` alias completely.

Bug 1906941 - Update kotlin jinja template import statement

---

CHANGELOG.md
glean_parser/templates/kotlin.geckoview.jinja2
tests/test_kotlin.py

This reverts commit 55f5e775ea4c63c81fd6d537695635ef6b99737b.

Bug 1912724 - Revert "Bug 1906941 - Update kotlin jinja template import statement (#740)"

---

CHANGELOG.md
glean_parser/templates/kotlin.geckoview.jinja2
tests/test_kotlin.py

This reverts commit 55f5e77.
This needs #744 to land and be released first in a patch release.
This one is then a breaking change to go into a major release.

 Reapply "Bug 1906941 - Update kotlin jinja template import statement (#740)

---

CHANGELOG.md
glean_parser/rust.py
tests/test_rust.py

Bug 1915744 - Rust codegen: use correctly named parameter

---

CHANGELOG.md
glean_parser/translate.py

When we switched from just printing the error to raising it as an exception, we accidentally left the `file` argument in. It's not needed and not accepted by ValueError.

Bug 1922086 - Remove now-unused keyword argument

---

glean_parser/templates/rust.jinja2

In Firefox we would like to be able to clone the payloads of object metrics so that we can report the contents in a profiler marker. See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1924518 for more details.

Derive `Clone` for generated object structures

---

CHANGELOG.md
glean_parser/templates/go_server.jinja2
tests/data/server_custom_ping_only_compare.go
tests/data/server_events_and_custom_ping_compare.go
tests/data/server_events_only_compare.go
tests/test-go/test.go.tmpl

The go server implementation is hardcoded to use stdout. As we add more server glean logs, this will make the output have more entries and be harder to read while developing.
Adjust the go server implementation to allow for a configurable writer. This will enable users of the go server implementation to choose where the logs are written to. When running in production it will have to supply stdout since that is where the ingestion side of things expects to find the logs.
made similar modifications to the server output locally and confirmed these different scenarios are all valid:
a Writer of `io.Discard` will produce no output
a Writer of a file will write logs to a file
a Writer of `os.Stdout` matches existing behavior
ran `make test-full` …

[go server] enable configurable writer

---

CHANGELOG.md
glean_parser/lint.py
tests/data/name_too_similar.yaml
tests/test_lint.py

bug 1934099 - New lint: metric names that differ only in punctuation

---

CHANGELOG.md
glean_parser/metrics.py
tests/test_parser.py

Bug 1933542 - Require `array` or `object` as the root type in object metrics

---

CHANGELOG.md
glean_parser/util.py

- doesn't include tests because Kotlin codegen will break in mozilla/glean if it's wrong. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1762858

Add 'uploader_capabilities' to util's ping_args to unbreak Kotlin codegen

---

glean_parser/lint.py
tests/test_lint.py

For custom units it's ok if they match t he name's suffix. The alternative encourages awkwardly naming things or omitting units entirely -- either action reduces the richness of information in the metric definition.

Bug 1950669 - Allow custom-defined units as a name suffix too

---

CHANGELOG.md
glean_parser/parser.py
tests/data/attribution.yaml
tests/data/bad_attribution.yamlx
tests/data/reserved_categories.yamlx
tests/test_parser.py

bug 1955428 - Permit use of reserved metric category 'glean' only for 'glean.{attribution|distribution}.ext' object metrics

---

CHANGELOG.md
glean_parser/lint.py
glean_parser/metrics.py
glean_parser/parser.py
glean_parser/util.py
tests/data/redefined_category.yamlx
tests/data/redefined_metric.yamlx
tests/data/redefined_ping.yamlx
tests/data/same_name_different_category.yaml
tests/test_lint.py

We don't want to forbid the redefinition of every YAML property, as we use that to save typing out similar definitions over and over again with YAML's spread operator `<<: *`
I got it far enough to catch the redefinition of a metric within the same category, which hopefully will be enough to get started with.

bug 1921089 - Forbid redefinition of metrics in definitions files

---

glean_parser/schemas/metrics.2-0-0.schema.yaml
glean_parser/schemas/pings.2-0-0.schema.yaml

Noticed these were not used anywhere.

Schemas: Remove unused definitions
